version: '3.8'

services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    container_name: ganache
    ports:
      - "7545:7545"
    networks:
      - blockchain-network
    environment:
      - GANCHES_FLAGS=-d

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=blockchain
    depends_on:
      - ganache
      - mysql
    networks:
      - blockchain-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - blockchain-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blockchain
    networks:
      - blockchain-network

networks:
  blockchain-network:
    driver: bridge
